### ISSUE TITLE
`convert_body()` called twice when preparing response

### ISSUE THREAD

**Issue by kennedymwavu** [ambiorix-web/ambiorix#76]
## description

for methods `send()`, `sendf()` and `text()` of the Response class, the function `convert_body()` is redundantly called twice: once in the methods themselves, and then again within the `response()` function, which each of these methods subsequently call.

## example

here's the current definition of `send()`:

```r
send = function(body, headers = NULL, status = NULL){
  deprecated_headers(headers)
  deprecated_status(status)
  headers <- private$.get_headers(headers)
  response(status = private$.get_status(status), headers = headers, body = convert_body(body))
}
```

in this method, `convert_body()` is called before passing `body` to `response()`.

however, the `response()` function also calls `convert_body()`:

```r
response <- function(body, headers = list(), status = 200L){
  assert_that(not_missing(body))
  res <- list(status = as.integer(status), headers = headers, body = convert_body(body))
  construct_response(res)
}
```

as a result, `convert_body()` is applied twice, causing unnecessary processing.

## suggestion

we should remove calls to `convert_body()` in the said methods of the Response class: `send()`, `sendf()` & `text()`, allowing `response()` to handle the body conversion consistently.

**Comment by JohnCoene** [comment]
Ah I missed that, well spotted
